### ISSUE TITLE
Some tests and returning fail when they work as expected

### ISSUE THREAD

**Issue by dcoloma** [AlejandroKZ/SistemaDeFicheros#4]
For instance, testBorrarArchivoDeDirectorioInexistente, in this case, as the file does not exist, the test executes a fail() (in the else clause) but I think the tes work as expected: the directory cannot be deleted.    

```
 if(sf.borrarArchivo("a", "C:/b", true)){
    System.out.println("---------Test Borrar Archivo Inexistente en C:---------");  
    sf.mostrarContenidoCluster();
    sf.mostrarContenidoInodos();
    sf.mostrarMapas();
}else fail();
```

**Comment by AlejandroKZ** [comment]
When I execute this method, I get an error, not to fail. And I think it is a good result, because we are trying to do an unsupported operation for the algorithm. And this mean that we need try to avoid or fix this situation.

**Comment by AlejandroKZ** [comment]
When I execute this method, I get an error, not to fail. And I think it is a good result, because we are trying to do an unsupported operation for the algorithm. And this mean that we need try to avoid or fix this situation.

**Comment by dcoloma** [comment]
oh, yeah, I overlooked to it. It makes sense. Thanks!
